name: 'Flyway Deploy'
 
on:
  push:
    branches:
      - master
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FLYWAY_EMAIL: ${{ secrets.FLYWAY_EMAIL }}
      FLYWAY_TOKEN: ${{ secrets.FLYWAY_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Flyway Deploy
        uses: docker://redgate/flyway:11
        with:
          args: >-
            prepare
            deploy
            -prepare.source=schemaModel
            -prepare.target=production
            -environment=production
            -environments.production.url="${{ secrets.FLYWAY_URL }}"
            -environments.production.user="${{ secrets.FLYWAY_USER }}"
            -environments.production.password="${{ secrets.FLYWAY_PASSWORD }}"
            -workingDirectory="/github/workspace/"
