name: Redgate Flyway
 
on:
  push:
    branches:
      - main
 
jobs:
  prepare:
    name: Redgate Flyway Prepare
    runs-on: ubuntu-latest
    env:
      FLYWAY_EMAIL: ${{ secrets.FLYWAY_EMAIL }}
      FLYWAY_TOKEN: ${{ secrets.FLYWAY_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Flyway
        uses: red-gate/setup-flyway@v1
    
      - name: Redgate Flyway Prepare
        run: |
          flyway prepare \
            -prepare.source=schemaModel \
            -prepare.target=production \
            -environments.production.url="${{ secrets.FLYWAY_URL }}" \
            -environments.production.user="${{ secrets.FLYWAY_USER }}" \
            -environments.production.password="${{ secrets.FLYWAY_PASSWORD }}"

      - name: Upload Deployment Script
        uses: actions/upload-artifact@v4
        with:
          name: database-deployment-script
          path: deployments/D__deployment.sql

  deploy:
    name: Redgate Flyway Deploy
    runs-on: ubuntu-latest
    needs: prepare
    environment:
      name: Production
    env:
      FLYWAY_EMAIL: ${{ secrets.FLYWAY_EMAIL }}
      FLYWAY_TOKEN: ${{ secrets.FLYWAY_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Flyway
        uses: red-gate/setup-flyway@v1

      - name: Download Deployment Script
        uses: actions/download-artifact@v4
        with:
          name: database-deployment-script
          path: deployments
      - name: Redgate Flyway Deploy
        run: |
          flyway deploy \
            -environment=production \
            -environments.production.url="${{ secrets.FLYWAY_URL }}" \
            -environments.production.user="${{ secrets.FLYWAY_USER }}" \
            -environments.production.password="${{ secrets.FLYWAY_PASSWORD }}"

    
