name: 'Flyway Migrate'
 
on:
  push:
    branches:
      - master
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run Flyway Migrate
        uses: docker://redgate/flyway:11
        with:
          args: >-
            migrate
            -workingDirectory="/github/workspace/"
            -url="${{ secrets.FLYWAY_URL }}"
            -user="${{ secrets.FLYWAY_USER }}"
            -password="${{ secrets.FLYWAY_PASSWORD }}"
