name: 'Flyway Migrate'
 
on:
  push:
    branches:
      - master
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: flyway-morning
      - name: Run Flyway Migrate
        uses: docker://redgate/flyway:11
        with:
          args: >-
            prepare -source=schemaModel -target=default -scriptFilename="D__deployment.sql"
            -workingDirectory="/github/workspace/"
            -url="${{ secrets.FLYWAY_URL }}"
            -user="${{ secrets.FLYWAY_USER }}"
            -password="${{ secrets.FLYWAY_PASSWORD }}"
        env:
           FLYWAY_EMAIL: ${{ secrets.FLYWAY_EMAIL }}
           FLYWAY_TOKEN: ${{ secrets.FLYWAY_TOKEN }}
      - name: Display deployment
        run: |
           cat D__deployment.sql
